version: "3.1"
services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  server:
    build: ./
    container_name: server
    command: yarn start
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/apidb
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - 3000:3000
